name: Combined Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    workflow_id: deploy

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build static file
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.event_name == 'workflow_dispatch'

    env:
      AWS_CLOUDFRONT_DISTRIBUTION_ID: E2OLQ8QC9NXQ5A
      AWS_CLOUDFRONT_DISTRIBUTION_ID_CNAME_REMOVE: E1QION2DS4X756

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Install jq
        run: sudo apt-get install jq

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://blue--www.blog.jamoroso.com
      
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Update DNS record
        run: aws route53 change-resource-record-sets --hosted-zone-id Z0308801UI1T6XDOPWTE --change-batch file://record_route53/dns-update.json

      - name: Remove CNAME from CloudFront
        run: |
          # Step 1: Retrieve the current CloudFront distribution configuration
          aws cloudfront get-distribution-config --id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID_CNAME_REMOVE }} > distribution-config.json

          # Step 2: Modify the configuration to remove the CNAME (you can use a script, or a command-line tool like jq)
          jq '.DistributionConfig.Aliases.Items = [] | .DistributionConfig.Aliases.Quantity = 0' distribution-config.json > modified-config.json

          # Step 3: Update the CloudFront distribution with the modified configuration
          aws cloudfront update-distribution --id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID_CNAME_REMOVE }} --if-match $(jq -r '.ETag' distribution-config.json) --distribution-config file://modified-config.json
 
